name: 'Checkout code and setup Node'
inputs:
    node-version:
        description: 'Node.js version'
        required: true
        default: '18.16.0'
    
    runs:
    using: 'composite'
    steps:
        - name: Check out code
        uses: actions/checkout@v2
        - name: Set up node
        uses: actions/setup-node@v3
        with:
            node-version: ${{ inputs.node-version }}
            registry-url: 'https://registry.npmjs.org'
      