on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Release type'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
      tags:
        description: 'Tag'
        required: false
        type: string
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Log Inputs
        run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}"

      - name: Read Package.json Version
        id: version
        run: ls -a

      - name: Print Version
        run: echo "The version in package.json is ${{ steps.version.outputs.version }}"
