name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release type'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
      tags:
        description: 'Tag'
        required: true
        default: 'beta'
        type: choice
        options:
          - latest
          - beta
          - dev
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Core - CD into correct folder
        run: echo "cd packages/core"

      - name: Core - Bump version
        run: npm version ${{ github.event.inputs.version }}

      - name: Core - Read Package.json Version
        id: version
        run: echo "::set-output name=version::$(jq -r .version package.json)"

      - name: Core - Create git tag
        run: git tag @scania/tegel@${{ steps.version.outputs.version }}

      - name: Core - Push git tag
        run: git push origin @scania/tegel@${{ steps.version.outputs.version }}

      - name: Core - Run build
        run: echo "The version in package.json is ${{ steps.version.outputs.version }}"

      - name: Core - Publish
        run: echo "The version in package.json is ${{ steps.version.outputs.version }}"
