name: Release @scania/tegel-react
on:
  workflow_dispatch:
    inputs:
      tegelVersion:
        description: 'Tegel version'
        required: true
        type: string

      nodeVersion:
        description: 'Node version'
        required: true
        default: '18.16.0'
        type: string

      tags:
        description: 'Tag'
        required: true
        default: 'beta'
        type: choice
        options:
          - latest
          - beta
          - dev

      dryRun:
        description: 'Dry run'
        required: false
        default: true
        type: boolean

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup project
        uses: ./.github/actions/setup-project
        with:
          node-version: ${{ github.event.inputs.tegelVersion }}

      - name: React - CD into correct folder
        run: echo "cd packages/react"

      - name: React - Remove package-lock
        run: echo "rm -rf package-lock.json"

      - name: React - npm install
        run: npm install

      - name: React - Install latest tegel package
        run: npm @scania/tegel@${{ github.event.inputs.tegelVersion }}

      - name: Set user
        run: git config --global user.name "Tegel - Scania" && git config --global user.email "tegel.design.system@gmail.com"

      - name: React - Bump version
        run: npm version ${{ github.event.inputs.tegelVersion }}

      - name: React - Read Package.json Version
        id: version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: React - Run build
        run: npm run build

      - name: React - Publish
        run: |
          if [ "${{ github.event.inputs.dryRun }}" == "true" ]; then
            npm publish --tag ${{ github.event.inputs.tags }} --dry-run
          else
            npm publish --tag ${{ github.event.inputs.tags }}
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Core - Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          title: release/@scania/tegel-react@${{ steps.version.outputs.version }}
          commit-message: Release of @scania/tegel@${{ steps.version.outputs.version }}
          branch: release/${{ steps.version.outputs.version }}
          delete-branch: true
