name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release type'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
      tags:
        description: 'Tag'
        required: true
        default: 'beta'
        type: choice
        options:
          - latest
          - beta
          - dev
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Core - CD into correct folder
        run: echo "cd packages/core"

      - name: Set user
        run: git config --global user.name "Martin Jarsäter" && git config --global user.email "martin.jarsater@hotmail.com"

      - name: Core - Bump version
        run: npm version ${{ github.event.inputs.version }}

      - name: Core - Read Package.json Version
        id: version
        run: echo "{version}={$(jq -r .version package.json)}" >> $GITHUB_OUTPUT

      - name: Core - Create git tag
        run: git tag @scania/tegel@${{ steps.version.outputs.version }}

      - name: Core - Push git tag
        run: git push origin @scania/tegel@${{ steps.version.outputs.version }}

      - name: Core - Run build
        run: echo "Building Core"

      - name: Core - Publish
        run: echo "npm run publish --tag ${{ github.event.inputs.tags }} --dry-run"

      - name: Commit and push branch
        run: |
          NEW_BRANCH_NAME="release/${{ steps.version.outputs.version }}"

          git checkout -b $NEW_BRANCH_NAME

          git add .

          git commit -m "Release:${{ steps.version.outputs.version }}"

          git push origin $NEW_BRANCH_NAME

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
