name: Release @scania/tegel
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release type'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

      nodeVersion:
        description: 'Node version'
        required: true
        default: '18.16.0'
        type: string

      tags:
        description: 'Tag'
        required: true
        default: 'beta'
        type: choice
        options:
          - latest
          - beta
          - dev

      dryRun:
        description: 'Dry run'
        required: false
        default: true
        type: boolean

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up node
        # Setup .npmrc file to publish to npm
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
          registry-url: 'https://registry.npmjs.org'

      - name: Save workspace
        uses: actions/upload-artifact@v2
        with:
          name: tegel-workspace
          path: . # Save the entire workspace
  npm_bump:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code from workspace
        uses: actions/download-artifact@v2
        with:
          name: tegel-workspace

      - name: Set Tegel user
        run: git config --global user.name "Tegel - Scania" && git config --global user.email "tegel.design.system@gmail.com"
      - name: Core - CD into correct folder
        run: echo "cd packages/core"

      - name: Core - Bump version
        run: npm version ${{ github.event.inputs.version }}

      - name: Core - Read Package.json Version
        id: version
        run: echo "action_version=$(jq -r .version package.json)" >> $GITHUB_ENV
  git_tag:
    runs-on: ubuntu-latest
    needs: npm_bump
    steps:
      - name: Checkout code from workspace
        uses: actions/download-artifact@v2
        with:
          name: tegel-workspace

      - name: Core - Create git tag
        run: git tag @scania/tegel@${{ env.action_version }}

      - name: Core - Push git tag
        run: git push origin @scania/tegel@${{ env.action_version }}

  build:
    runs-on: ubuntu-latest
    needs: git_tag
    steps:
      - name: Checkout code from workspace
        uses: actions/download-artifact@v2
        with:
          name: tegel-workspace

      - name: Core - npm install
        run: npm install

      - name: Core - Run build
        run: npm run build

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code from workspace
        uses: actions/download-artifact@v2
        with:
          name: tegel-workspace

      - name: Core - Publish
        run: |
          if [ "${{ github.event.inputs.dryRun }}" == "true" ]; then
            npm publish --tag ${{ github.event.inputs.tags }} --dry-run
          else
            npm publish --tag ${{ github.event.inputs.tags }}
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create_pr:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout code from workspace
        uses: actions/download-artifact@v2
        with:
          name: tegel-workspace

      - name: Core - Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          title: release/@scania/tegel@${{ env.action_version }}
          commit-message: Release of @scania/tegel@${{ env.action_version }}
          branch: release/${{ env.action_version }}
          delete-branch: true
